samples: /data/Priyanka/other_pipelines/iCOMIC/Test/DNA-Seq/samples.tsv
samples_new: /data/Priyanka/other_pipelines/iCOMIC/samples_new.tsv
units: /data/Priyanka/other_pipelines/iCOMIC/Test/DNA-Seq/units.tsv
units_new: /data/Priyanka/other_pipelines/iCOMIC/units_new.tsv
ref: 
  name: GRCh38.86
#  genome: /data/Priyanka/other_pipelines/iCOMIC/Test/DNA-Seq/ref/genome.chr21.fa
  genome: /data/anjana/hg38.fa
  genome-name: genome.chr21.fa
#  known-variants: /data/Priyanka/other_pipelines/iCOMIC/Test/DNA-Seq/ref/dbsnp.vcf.gz
processing: 
  remove-duplicates: true
index: 
  BWA_MEM: /data/Priyanka/other_pipelines/iCOMIC/Test/DNA-Seq/ref/genome.chr21.fa
params: 
  cutadapt: '--threads 1' 
  GATK_HC: 
    HaplotypeCaller: '' 
    GenotypeGVCFs: '' 
    BaseRecalibrator: '' 
    VariantRecalibrator: '' 
  bcftools_call: '' 
  BWA_MEM: '' 
  GEM3: '' 
  SnpEff: '-Xmx4g' 
  freebayes: '' 
  mutect2: ''
  picard: 
    MarkDuplicates: REMOVE_DUPLICATES=true 
filtering:
  vqsr: false
  hard:
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"
