units: units.tsv 
ref: 
  index-hisat2: /home/priyanka/Desktop/test_env/iCOMIC/Demo_rna/index/hisat2/ 
  annotation: /home/priyanka/Desktop/test_env/iCOMIC/Demo_rna/chr22_refGene.gtf
  fasta: /home/priyanka/Desktop/test_env/iCOMIC/Demo_rna/hg38.chr22.fa
threads: 1
params: 
  cutadapt: ' --adapter AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT ' 
  hisat2 : ''
  HTseq : ''
  deseq2 : ''
sample: /home/priyanka/Desktop/test_env/iCOMIC/Demo_rna/samples
