#################### Configuration of Test Data ################


ref:
  #the STAR index
  index-star: "/data/Priyanka/other_pipelines/rna-seq-star-deseq2-master/Test_Run/Ref/star-index/"
  index-hisat2: "/data/Priyanka/other_pipelines/rna-seq-star-deseq2-master/Test_Run/Ref/hisat2-index/hisat2-index"
  index-salmon: "/data/Priyanka/other_pipelines/rna-seq-star-deseq2-master/Test_Run/Ref/salmon-index/"
  index-bowtie2: "/data/Priyanka/other_pipelines/rna-seq-star-deseq2-master/Test_Run/Ref/bowtie2-index/bowtie2-index"
  # gtf file with transcripts
  annotation: "/data/Priyanka/other_pipelines/rna-seq-star-deseq2-master/Test_Run/Ref/gencode/gencode.v29.annotation.gtf"
  fasta: "/data/Priyanka/other_pipelines/rna-seq-star-deseq2-master/Test_Run/Ref/gencode/GRCh38.primary_assembly.genome.fa"
  transcript: "/data/Priyanka/other_pipelines/rna-seq-star-deseq2-master/Test_Run/Ref/gencode/gencode.v29.transcripts.fa"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    #TNBC-vs-Non-TNBC:
    case-vs-control:
      - case
      - control

params:
  star: "--quantMode GeneCounts --limitBAMsortRAM 10000000000 --outSAMattrIHstart 0" #--sjdbOverhang 150
