include: "rules/common_rna.smk"
rule all:
  input:
    expand('results/aligner_results/hisat2/{sample}_{condition}_Rep{rep}.sam', sample=samples, condition=type, rep=reps),
    expand('results/aligner_results/hisat2/{sample}_{condition}_Rep{rep}.bam', sample=samples, condition=type, rep=reps),
    expand('results/em_results/{sample}_{condition}_Rep{rep}.counts', sample=samples, condition=type, rep=reps),
    "results/em_results/emtable.tsv",
    expand('results/de_results/DESeq2_normalized_counts.txt'),
    "results/multiqc/multiqc.html",
include: "rules/hisat2.smk" 
include: "rules/HTseq.smk" 
include: "rules/deseq2.smk" 
